apiVersion: v1
kind: Service
metadata:
  name: resume-analyzer-service
spec:
  type: NodePort
  selector:
    app: resume-analyzer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
